version: '3.8'
services:

  apiserver:
    build:
      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    restart: always
    ports:
      - 20000:8000
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./:/ayame
    command: /bin/sh -c  "cd /ayame && uvicorn app.main:app --reload --host 0.0.0.0 --proxy-headers --reload-dir ./app"
    logging:
     driver: "json-file"
     options:
       max-size: "1m"
       max-file: "1"
  
  mongodb:
    image: mongo
    restart: always
    environment:
      -  'MONGODB_USER=user' 
      -  'MONGODB_PASS=password'
    volumes:
      -  ./mongodb:/data/db

    command: 
      - --wiredTigerCollectionBlockCompressor
      - zstd


  mongo-express:
    ports:
      - 20001:8081
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password'
    image: mongo-express
    