version: '3.1'
services:

  apiserver:
    image: python:3.8-alpine
    depends_on:
      - mongodb
    restart: always
    ports:
      - 6003:8000
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./python_script:/fastapi
      - ./update:/update
    command: /bin/sh -c  "/fastapi/install_module.sh && cd /fastapi && uvicorn main:app --reload --host 0.0.0.0"
  
  mongodb:
    image: mongo
    restart: always
    environment:
      -  'MONGODB_USER=user' 
      -  'MONGODB_PASS=password'
    volumes:
      -  ./mongodb:/data/db

    command: 
      - --wiredTigerCollectionBlockCompressor
      - zstd


  mongo-express:
    ports:
      - 6004:8081
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
      - 'ME_CONFIG_BASICAUTH_USERNAME=user'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password'
    image: mongo-express
